version: '3'
services:
  otp:
    build:
      context: ./Dockerfiles/$otpversion
      dockerfile: Dockerfile
    volumes:
    - ./data:/app/data
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    # environment:
    #   - JAVA_MAX_MEMORY=-Xmx8G
    # command: tail -F anything
    
networks:
  default:
    name: trufi-server
