version: '3'
services:
  otp_old:
    build:
      context: ./Dockerfiles/1.5.0
      dockerfile: Dockerfile
    volumes:
    - ./data:/app/data
    restart: unless-stopped
    ports:
      - 8080:8080
  otp_new:
    build:
      context: ./Dockerfiles/2.4.0
      dockerfile: Dockerfile
    volumes:
    - ./data:/app/data
    restart: unless-stopped
    ports:
      - 9090:8080
    # environment:
    #   - JAVA_MAX_MEMORY=-Xmx8G
    # command: tail -F anything
    
networks:
  default:
    name: trufi-server
