#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Available OTP versions
AVAILABLE_VERSIONS=("1.5.0" "2.0.0" "2.2.0" "2.4.0" "2.7.0" "2.8.1")

print_header() {
    echo -e "${BLUE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║          OpenTripPlanner Server Setup                        ║"
    echo "║          Trufi Association                                   ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_usage() {
    echo -e "${YELLOW}Usage:${NC}"
    echo "  $0 --gtfs <path> --pbf <path> [--version <version>]"
    echo ""
    echo -e "${YELLOW}Options:${NC}"
    echo "  --gtfs <path>      Path to GTFS file (.zip) or directory containing GTFS files"
    echo "  --pbf <path>       Path to OSM PBF file (.osm.pbf)"
    echo "  --version <ver>    OTP version to use (default: 2.8.1)"
    echo "  --help             Show this help message"
    echo ""
    echo -e "${YELLOW}Available OTP versions:${NC}"
    for v in "${AVAILABLE_VERSIONS[@]}"; do
        if [ "$v" = "2.8.1" ]; then
            echo -e "  ${GREEN}$v${NC} (recommended)"
        else
            echo "  $v"
        fi
    done
    echo ""
    echo -e "${YELLOW}Examples:${NC}"
    echo "  $0 --gtfs ./my-gtfs.zip --pbf ./my-region.osm.pbf"
    echo "  $0 --gtfs ./gtfs-folder/ --pbf ./city.osm.pbf --version 2.7.0"
}

check_file_exists() {
    if [ ! -e "$1" ]; then
        echo -e "${RED}Error: File or directory not found: $1${NC}"
        exit 1
    fi
}

validate_version() {
    local version=$1
    for v in "${AVAILABLE_VERSIONS[@]}"; do
        if [ "$v" = "$version" ]; then
            return 0
        fi
    done
    echo -e "${RED}Error: Invalid OTP version: $version${NC}"
    echo -e "${YELLOW}Available versions: ${AVAILABLE_VERSIONS[*]}${NC}"
    exit 1
}

# Default values
OTP_VERSION="2.8.1"
GTFS_PATH=""
PBF_PATH=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --gtfs)
            GTFS_PATH="$2"
            shift 2
            ;;
        --pbf)
            PBF_PATH="$2"
            shift 2
            ;;
        --version)
            OTP_VERSION="$2"
            shift 2
            ;;
        --help|-h)
            print_header
            print_usage
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            print_usage
            exit 1
            ;;
    esac
done

print_header

# Validate required arguments
if [ -z "$GTFS_PATH" ] || [ -z "$PBF_PATH" ]; then
    echo -e "${RED}Error: Both --gtfs and --pbf are required${NC}"
    echo ""
    print_usage
    exit 1
fi

# Validate files exist
check_file_exists "$GTFS_PATH"
check_file_exists "$PBF_PATH"

# Validate version
validate_version "$OTP_VERSION"

echo -e "${GREEN}Configuration:${NC}"
echo "  GTFS:    $GTFS_PATH"
echo "  PBF:     $PBF_PATH"
echo "  Version: $OTP_VERSION"
echo ""

# Create data directory
echo -e "${BLUE}Setting up data directory...${NC}"
mkdir -p data

# Copy GTFS file (keep as zip, OTP can read it directly)
echo -e "${BLUE}Copying GTFS file...${NC}"
GTFS_FILENAME=$(basename "$GTFS_PATH")
cp "$GTFS_PATH" "data/$GTFS_FILENAME"

# Copy PBF file
echo -e "${BLUE}Copying PBF file...${NC}"
PBF_FILENAME=$(basename "$PBF_PATH")
cp "$PBF_PATH" "data/$PBF_FILENAME"

# Copy OTP config files for selected version
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/Dockerfiles/$OTP_VERSION/config"
echo -e "${BLUE}Copying OTP config files for version $OTP_VERSION...${NC}"
cp "$CONFIG_DIR"/*.json data/

# Create .env file
echo -e "${BLUE}Creating .env file...${NC}"
cat > .env << EOF
# OTP Server Configuration
# Generated by init.sh

# OTP version to use
otpversion=$OTP_VERSION
EOF

# Remove old graph if exists
if [ -f "data/graph.obj" ]; then
    echo -e "${YELLOW}Removing old graph.obj to force rebuild...${NC}"
    rm data/graph.obj
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Setup complete!                                             ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Start the server:"
echo -e "     ${BLUE}docker-compose up${NC}"
echo ""
echo "  2. Or run in background:"
echo -e "     ${BLUE}docker-compose up -d${NC}"
echo ""
echo "  3. Access the API at:"
echo -e "     ${BLUE}http://localhost:8080/otp/${NC}"
echo ""
echo -e "${YELLOW}Note:${NC} The first run will build the routing graph from your data."
echo "      This may take several minutes depending on the size of your data."
